# Generated by Django 2.2.26 on 2022-12-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sample_id', models.BigIntegerField()),
                ('examination_id', models.IntegerField()),
                ('result', models.CharField(blank=True, max_length=5000, null=True)),
                ('recording_time', models.DateTimeField(blank=True, null=True)),
                ('recorded_by', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'result',
                'managed': True,
                'unique_together': {('sample_id', 'examination_id')},
            },
        ),
    ]
