# Generated by Django 2.2.28 on 2022-12-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('food_id', models.CharField(blank=True, max_length=40, null=True)),
                ('gm', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=200, null=True)),
                ('recording_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'intake',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Myfood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('calcium', models.IntegerField(blank=True, null=True)),
                ('phosphorus', models.IntegerField(blank=True, null=True)),
                ('potassium', models.IntegerField(blank=True, null=True)),
                ('sodium', models.IntegerField(blank=True, null=True)),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('carbohydrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=100, null=True)),
                ('recording_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'myfood',
                'managed': False,
            },
        ),
    ]
